'use client'
import { useMemo,useState } from 'react'
const ITEMS=[
 {id:1,title:'Cours 3 — Le present perfect',type:'Vidéo',meta:'24 min · HD',week:3,new:true},{id:2,title:'Grammaire B2 — Récapitulatif',type:'PDF',meta:'18 pages · 2,4 Mo',week:3,new:false},{id:3,title:'Exercices — Present perfect',type:'Exercice',meta:'12 exercices · 0,8 Mo',week:3,new:true},{id:4,title:'QCM Semaine 3 — Évaluation',type:'QCM',meta:'5 questions · 15 min',week:3,new:false},{id:5,title:'Cours 2 — Le prétérit simple',type:'Vidéo',meta:'19 min · HD',week:2,new:false},{id:6,title:'Vocabulaire thématique B2',type:'PDF',meta:'8 pages · 1,1 Mo',week:2,new:false},{id:7,title:'Exercices — Conjugaison avancée',type:'Exercice',meta:'10 exercices · 0,6 Mo',week:2,new:false},{id:8,title:'Cours 1 — Introduction B2',type:'Vidéo',meta:'15 min · HD',week:1,new:false},{id:9,title:'QCM Semaine 1 — Diagnostique',type:'QCM',meta:'5 questions · 10 min',week:1,new:false},
]
export default function RessourcesPage(){
 const [query,setQuery]=useState('');const[filter,setFilter]=useState('Tous');const[view,setView]=useState<'grid'|'list'>('grid');const[page,setPage]=useState(1);const[active,setActive]=useState<typeof ITEMS[0]|null>(null);const perPage=6
 const filtered=useMemo(()=>ITEMS.filter(x=>(filter==='Tous'||x.type===filter)&&`${x.title} ${x.type}`.toLowerCase().includes(query.toLowerCase())),[query,filter]);const pages=Math.max(1,Math.ceil(filtered.length/perPage));const visible=filtered.slice((page-1)*perPage,page*perPage)
 return <div className="library-page resource-library">
  <header className="library-header"><div><div className="page-breadcrumb"><span>EDUOS</span><span>›</span><span>Ressources</span></div><h1>Ressources du cours</h1><p>Anglais B2 · Supports, vidéos et évaluations.</p></div><div className="resource-progress"><span>Progression</span><strong>67%</strong><i><span/></i></div></header>
  <div className="library-toolbar"><label><span>⌕</span><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Rechercher une ressource..." /></label><select value={filter} onChange={e=>{setFilter(e.target.value);setPage(1)}}><option>Tous</option><option>Vidéo</option><option>PDF</option><option>Exercice</option><option>QCM</option></select><div className="library-view"><button className={view==='grid'?'active':''} onClick={()=>setView('grid')} aria-label="Grille"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/></svg></button><button className={view==='list'?'active':''} onClick={()=>setView('list')} aria-label="Liste"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M8 6h13M8 12h13M8 18h13M3 6h.01M3 12h.01M3 18h.01"/></svg></button></div></div>
  <div className={`library-items resource-items ${view}`}>{visible.map(item=><article key={item.id}>
    <div className="resource-card-top"><span className={`library-icon ${item.type.toLowerCase()}`}>{item.type==='Vidéo'?'▶':item.type==='QCM'?'?':item.type==='Exercice'?'✓':'PDF'}</span>{item.new&&<span className="resource-new">Nouveau</span>}</div>
    <div className="resource-card-copy"><small>{item.type}</small><h2>{item.title}</h2><div><span>{item.meta}</span><em>Sem. {item.week}</em></div></div>
    <div className="library-actions"><button onClick={()=>setActive(item)}>{item.type==='Vidéo'?'Regarder la vidéo':item.type==='QCM'?'Passer le QCM':item.type==='Exercice'?'Télécharger les exercices':'Télécharger le PDF'}</button></div>
  </article>)}{!visible.length&&<div className="library-empty">Aucune ressource trouvée.</div>}</div>
  <div className="library-pagination"><span>{filtered.length} ressource{filtered.length>1?'s':''}</span><div><button disabled={page===1} onClick={()=>setPage(page-1)}>←</button><span>{page} / {pages}</span><button disabled={page===pages} onClick={()=>setPage(page+1)}>→</button></div></div>
  {active&&<div className="library-overlay" onMouseDown={e=>e.target===e.currentTarget&&setActive(null)}><div className="library-preview"><header><span>{active.type.toUpperCase()}</span><button onClick={()=>setActive(null)}>×</button></header><div className="resource-preview"><span>{active.type==='Vidéo'?'▶':active.type==='QCM'?'?':'PDF'}</span><h2>{active.title}</h2><p>{active.meta} · Semaine {active.week}</p></div><button onClick={()=>setActive(null)}>{active.type==='QCM'?'Démarrer l’évaluation':'Marquer comme terminé'}</button></div></div>}
 </div>
}
